/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisciplineRouteImport } from './routes/$discipline'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandDiscoveryRouteImport } from './routes/brand-discovery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GraphicDesignRouteImport } from './routes/graphic-design'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as ProductDesignRouteImport } from './routes/product-design'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as ApiBrandDiscoveryRouteImport } from './routes/api.brand-discovery'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as VisualIdentityProjectIdRouteImport } from './routes/visual-identity.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/$discipline',
  path: '/$discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDiscoveryRoute = BrandDiscoveryRouteImport.update({
  id: '/brand-discovery',
  path: '/brand-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicDesignRoute = GraphicDesignRouteImport.update({
  id: '/graphic-design',
  path: '/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDesignRoute = ProductDesignRouteImport.update({
  id: '/product-design',
  path: '/product-design',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBrandDiscoveryRoute = ApiBrandDiscoveryRouteImport.update({
  id: '/api/brand-discovery',
  path: '/api/brand-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualIdentityProjectIdRoute = VisualIdentityProjectIdRouteImport.update({
  id: '/visual-identity/$projectId',
  path: '/visual-identity/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand-discovery': typeof BrandDiscoveryRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/photography': typeof PhotographyRoute
  '/product-design': typeof ProductDesignRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/brand-discovery': typeof ApiBrandDiscoveryRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/visual-identity/$projectId': typeof VisualIdentityProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/about': typeof AboutRoute
  '/brand-discovery': typeof BrandDiscoveryRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/photography': typeof PhotographyRoute
  '/product-design': typeof ProductDesignRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/brand-discovery': typeof ApiBrandDiscoveryRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/visual-identity/$projectId': typeof VisualIdentityProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand-discovery': typeof BrandDiscoveryRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/photography': typeof PhotographyRoute
  '/product-design': typeof ProductDesignRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/brand-discovery': typeof ApiBrandDiscoveryRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/visual-identity/$projectId': typeof VisualIdentityProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$discipline'
    | '/about'
    | '/admin'
    | '/brand-discovery'
    | '/contact'
    | '/graphic-design'
    | '/photography'
    | '/product-design'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/invoices'
    | '/admin/projects'
    | '/api/brand-discovery'
    | '/api/contact'
    | '/blog/$slug'
    | '/projects/$projectId'
    | '/visual-identity/$projectId'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$discipline'
    | '/about'
    | '/brand-discovery'
    | '/contact'
    | '/graphic-design'
    | '/photography'
    | '/product-design'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/invoices'
    | '/admin/projects'
    | '/api/brand-discovery'
    | '/api/contact'
    | '/blog/$slug'
    | '/projects/$projectId'
    | '/visual-identity/$projectId'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$discipline'
    | '/about'
    | '/admin'
    | '/brand-discovery'
    | '/contact'
    | '/graphic-design'
    | '/photography'
    | '/product-design'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/invoices'
    | '/admin/projects'
    | '/api/brand-discovery'
    | '/api/contact'
    | '/blog/$slug'
    | '/projects/$projectId'
    | '/visual-identity/$projectId'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisciplineRoute: typeof DisciplineRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrandDiscoveryRoute: typeof BrandDiscoveryRoute
  ContactRoute: typeof ContactRoute
  GraphicDesignRoute: typeof GraphicDesignRoute
  PhotographyRoute: typeof PhotographyRoute
  ProductDesignRoute: typeof ProductDesignRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBrandDiscoveryRoute: typeof ApiBrandDiscoveryRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  VisualIdentityProjectIdRoute: typeof VisualIdentityProjectIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$discipline': {
      id: '/$discipline'
      path: '/$discipline'
      fullPath: '/$discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-discovery': {
      id: '/brand-discovery'
      path: '/brand-discovery'
      fullPath: '/brand-discovery'
      preLoaderRoute: typeof BrandDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-design': {
      id: '/graphic-design'
      path: '/graphic-design'
      fullPath: '/graphic-design'
      preLoaderRoute: typeof GraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-design': {
      id: '/product-design'
      path: '/product-design'
      fullPath: '/product-design'
      preLoaderRoute: typeof ProductDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/brand-discovery': {
      id: '/api/brand-discovery'
      path: '/api/brand-discovery'
      fullPath: '/api/brand-discovery'
      preLoaderRoute: typeof ApiBrandDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-identity/$projectId': {
      id: '/visual-identity/$projectId'
      path: '/visual-identity/$projectId'
      fullPath: '/visual-identity/$projectId'
      preLoaderRoute: typeof VisualIdentityProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisciplineRoute: DisciplineRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BrandDiscoveryRoute: BrandDiscoveryRoute,
  ContactRoute: ContactRoute,
  GraphicDesignRoute: GraphicDesignRoute,
  PhotographyRoute: PhotographyRoute,
  ProductDesignRoute: ProductDesignRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBrandDiscoveryRoute: ApiBrandDiscoveryRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  VisualIdentityProjectIdRoute: VisualIdentityProjectIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
